<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'category_id' => 1,
                'name' => 'One Piece Volume 1',
                'age' => '12',
                'author' => 'Eiichiro Oda',
                'images' => 'one_piece_1.jpg',
                'images_sup' => 'one_piece_1_sup.jpg',
                'publisher' => 'Shonen Jump',
                'quantity' => 100,
                'price' => 80000,
                'sale' => 0,
                'price_sale' => 80000,
                'detail' => 'Cuộc phiêu lưu của Luffy',
                'categ' => 'Manga',
                'status' => 1,
                'is_active' => 1,
                'language' => 'Tiếng Anh',
                'weight' => 200,
                'size' => 'A5',
                'quantity_buy' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Naruto Volume 1',
                'age' => '10',
                'author' => 'Masashi Kishimoto',
                'images' => 'naruto_1.jpg',
                'images_sup' => 'naruto_1_sup.jpg',
                'publisher' => 'Shonen Jump',
                'quantity' => 80,
                'price' => 75000,
                'sale' => 10,
                'price_sale' => 67500,
                'detail' => 'Hành trình trở thành Hokage',
                'categ' => 'Manga',
                'status' => 1,
                'is_active' => 1,
                'language' => 'Tiếng Anh',
                'weight' => 200,
                'size' => 'A5',
                'quantity_buy' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Dragon Ball Volume 1',
                'age' => '8',
                'author' => 'Akira Toriyama',
                'images' => 'dragon_ball_1.jpg',
                'images_sup' => 'dragon_ball_1_sup.jpg',
                'publisher' => 'Shonen Jump',
                'quantity' => 120,
                'price' => 70000,
                'sale' => 5,
                'price_sale' => 66500,
                'detail' => 'Hành trình tìm kiếm bảy viên ngọc rồng',
                'categ' => 'Manga',
                'status' => 1,
                'is_active' => 1,
                'language' => 'Tiếng Anh',
                'weight' => 200,
                'size' => 'A5',
                'quantity_buy' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Tower of God Volume 1',
                'age' => '13',
                'author' => 'SIU',
                'images' => 'tower_of_god_1.jpg',
                'images_sup' => 'tower_of_god_1_sup.jpg',
                'publisher' => 'Korean Comics',
                'quantity' => 60,
                'price' => 85000,
                'sale' => 0,
                'price_sale' => 85000,
                'detail' => 'Cuộc thăm dò tường thành bí ẩn',
                'categ' => 'Manhwa',
                'status' => 1,
                'is_active' => 1,
                'language' => 'Tiếng Anh',
                'weight' => 200,
                'size' => 'A5',
                'quantity_buy' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Mo Dao Zu Shi Vol 1',
                'age' => '14',
                'author' => 'Huyền Hư Mai Lâm',
                'images' => 'mo_dao_zu_shi_1.jpg',
                'images_sup' => 'mo_dao_zu_shi_1_sup.jpg',
                'publisher' => 'Jitui Culture',
                'quantity' => 50,
                'price' => 95000,
                'sale' => 15,
                'price_sale' => 80750,
                'detail' => 'Cái Tên Dị Giả - Truyện kinh điển mạo hiểm',
                'categ' => 'Manhua',
                'status' => 1,
                'is_active' => 1,
                'language' => 'Tiếng Anh',
                'weight' => 200,
                'size' => 'A5',
                'quantity_buy' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
